export const FETCH_INGAMECATEGORIES_BEGIN = "FETCH_INGAMECATEGORIES_BEGIN";
export const FETCH_INGAMECATEGORIES_SUCCESS = "FETCH_INGAMECATEGORIES_SUCCESS";
export const FETCH_INGAMECATEGORIES_FAILURE = "FETCH_INGAMECATEGORIES_FAILURE";
